# Generated by Django 3.1.7 on 2021-02-24 09:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Image2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Image3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.DeleteModel(
            name='demo',
        ),
    ]
