# Generated by Django 3.1.7 on 2021-02-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210224_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='about',
            new_name='aboutcontent',
        ),
    ]
