# Generated by Django 3.1.7 on 2021-02-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210224_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='aboutcontent',
            field=models.TextField(),
        ),
    ]
