# Generated by Django 3.1.7 on 2021-02-24 12:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210224_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Image2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Image3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('aboutimage1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('aboutimage2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('aboutimage3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('aboutcontent', models.TextField()),
                ('servicecontent', models.TextField()),
                ('serviceimage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('succestory1', models.TextField()),
                ('succestory2', models.TextField()),
                ('successimage1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('successimage2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Image2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Image3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('aboutimage1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('aboutimage2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('aboutimage3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('aboutcontent', models.TextField()),
                ('servicecontent', models.TextField()),
                ('serviceimage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('succestory1', models.TextField()),
                ('succestory2', models.TextField()),
                ('successimage1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('successimage2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Image2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Image3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('aboutimage1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('aboutimage2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('aboutimage3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('aboutcontent', models.TextField()),
                ('servicecontent', models.TextField()),
                ('serviceimage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('succestory1', models.TextField()),
                ('succestory2', models.TextField()),
                ('successimage1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('successimage2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
