# Generated by Django 3.1.7 on 2021-02-25 04:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_enquiry_quickquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='aboutimage4',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='aboutimage4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='aboutimage5',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='aboutimage5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='aboutimage6',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='aboutimage6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='aboutimage7',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='aboutimage7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='aboutimage4',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='aboutimage4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='aboutimage5',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='aboutimage5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='aboutimage6',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='aboutimage6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='aboutimage7',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='aboutimage7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='aboutimage4',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='aboutimage4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='aboutimage5',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='aboutimage5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='aboutimage6',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='aboutimage6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='aboutimage7',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='aboutimage7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='Image1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='bannerimage1'),
        ),
        migrations.AlterField(
            model_name='business',
            name='Image2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='bannerimage2'),
        ),
        migrations.AlterField(
            model_name='business',
            name='Image3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='bannerimage3'),
        ),
        migrations.AlterField(
            model_name='business',
            name='aboutimage1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='aboutimage1'),
        ),
        migrations.AlterField(
            model_name='business',
            name='aboutimage2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='aboutimage2'),
        ),
        migrations.AlterField(
            model_name='business',
            name='aboutimage3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='aboutimage3'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='Image1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='bannerimage1'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='Image2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='bannerimage2'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='Image3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='bannerimage3'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='aboutimage1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='aboutimage1'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='aboutimage2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='aboutimage2'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='aboutimage3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='aboutimage3'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Image1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='bannerimage1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Image2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='bannerimage2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Image3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='bannerimage3'),
        ),
        migrations.AlterField(
            model_name='student',
            name='aboutimage1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='aboutimage1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='aboutimage2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='aboutimage2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='aboutimage3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='aboutimage3'),
        ),
    ]
