# Generated by Django 3.1.7 on 2021-02-25 04:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210225_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='successimage1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='successimage1'),
        ),
        migrations.AlterField(
            model_name='business',
            name='successimage2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='successimage2'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='successimage1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='successimage1'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='successimage2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='successimage2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='successimage1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='successimage1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='successimage2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='successimage2'),
        ),
    ]
