# Generated by Django 3.1.7 on 2021-02-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210225_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='solution',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='solution',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='solution',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
