# Generated by Django 3.1.7 on 2021-02-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210226_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickquery',
            old_name='email',
            new_name='qemail',
        ),
        migrations.RenameField(
            model_name='quickquery',
            old_name='message',
            new_name='qmessage',
        ),
        migrations.RenameField(
            model_name='quickquery',
            old_name='name',
            new_name='qname',
        ),
    ]
